
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { customStorage } from '@/utils/customStorage';

const SUPABASE_URL = "https://vklytnmygsdihdbxzhlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbHl0bm15Z3NkaWhkYnh6aGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDQ3MjksImV4cCI6MjA2MzIyMDcyOX0.JWaAnm_FQ8idv8Ngbjq5n3ms4j6os6jXg4mzWBsRpno";

// Get the current domain for redirects (use production URL if available)
const getRedirectUrl = () => {
  // For Lovable production deployment
  const productionUrl = 'https://meeting-cost-insight.lovable.so';
  
  // For local development fallback
  const localUrl = typeof window !== 'undefined' ? `${window.location.protocol}//${window.location.host}` : '';
  
  // Return the appropriate URL based on environment
  return productionUrl || localUrl;
};

// Debug any errors when initializing
console.log("🔑 Supabase initializing...");

// Create a single client instance to be used throughout the app
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: customStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce', // More secure than implicit flow
      // Fix the property name to 'redirectTo' (camelCase)
      redirectTo: `${getRedirectUrl()}/auth/callback`
    },
    global: {
      headers: {
        'X-Client-Info': 'lovable-app'
      }
    }
  }
);

// Log initialization complete
console.log("✅ Supabase client initialized with redirectTo:", `${getRedirectUrl()}/auth/callback`);

// Update the redirect URL for authentication methods
supabase.auth.setSession({
  access_token: '',
  refresh_token: ''
});

// Verbose session debugging
try {
  console.log("🔍 Checking initial Supabase session...");
  supabase.auth.getSession().then(({ data, error }) => {
    if (error) {
      console.error("❌ Error getting initial session:", error.message);
      return;
    }
    
    const { session } = data;
    if (session) {
      const now = Math.floor(Date.now() / 1000);
      const expiresAt = session.expires_at as number;
      const timeLeft = expiresAt - now;
      
      console.log(`✅ Session found: ${session.user.email}`);
      console.log(`⏱️ Session expires in: ${Math.floor(timeLeft / 60)} minutes`);
    } else {
      console.log("ℹ️ No active session found");
    }
  }).catch(err => {
    console.error("❌ Failed to check initial session:", err);
  });
} catch (e) {
  console.error("❌ Critical error during session check:", e);
}

// Monitor auth state changes
try {
  supabase.auth.onAuthStateChange((event, newSession) => {
    console.log(`🔔 Auth state changed: ${event}`, newSession ? 
      `User: ${newSession.user.email}` : "No session");
    
    if (event === 'TOKEN_REFRESHED') {
      console.log("🔄 Auth token refreshed automatically");
    }
  });
} catch (e) {
  console.error("❌ Failed to set up auth state change listener:", e);
}
